# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift
script:
- set -o pipefail && xcodebuild test -project TKFormTextFieldDemo.xcodeproj -scheme TKFormTextFieldDemoUITests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
# - set -o pipefail && xcodebuild -project TKFormTextFieldDemo.xcodeproj -scheme TKFormTextField -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty


# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# script:
# - set -o pipefail && xcodebuild test -workspace Example/TKFormTextField.xcworkspace -scheme TKFormTextField-Example -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
